### ISSUE TITLE
Autenticación y autorización con Google o GitHub

### ISSUE THREAD

**Issue by salva200** [salvador-diaz/salvador-diaz-lamp#3]
## Contexto
Actualmente no se discrimina el acceso a recursos según el usuario que accede a la página.

## Requisitos
- [x] Investigar integración de registro/login mediante Google o Github.
- [x] Implementar bases para la autenticación y autorización en la web.

**Comment by salvador-diaz** [comment]
[Developer Docs - Integra el Acceso con Google en tu app web](https://developers.google.com/identity/sign-in/web/sign-in?hl=es-419)

**Comment by salva200** [comment]
La autenticación y autorización son realizados mediante el servicio [OAuth2.0 que ofrece Google](https://developers.google.com/identity/openid-connect/openid-connect). Se procede a desarrollar la integración con la app

## Pasos previos
Registrar mi aplicación web en Google API Console:

1. Configurar pantalla de consentimiento OAuth.
	- Definir nombre y dominio del sitio.
	- Definir los permisos que pedirá el sitio.
2. Crear cedencial de cliente OAuth.
	- Nombre interno de la app.
	- URI/s de redirección.

Entonces Google Console provee un client ID y un client secret los cuales identifican a la aplicación. Serán guardados en las variables de entorno como:
```php
const GOOGLE_OAUTH_CLIENTID = "";
const GOOGLE_OAUTH_SECRET = "";
```

## Dependencias
Se ve necesario instalar el gestor de dependencias [composer](https://getcomposer.org/doc/00-intro.md) para requerir las siguientes librerías mantenidas por Google:
- [google-api-php-client](https://github.com/googleapis/google-api-php-client)
- [google-api-php-client-services](https://github.com/googleapis/google-api-php-client-services) (requiere google-api-php-client)


## Flujo OAuth2.0
 - Usuario accede a mi aplicación web.
 - Usuario elige registrarse/loguearse con Google.
 - Mi aplicación dirige al usuario a loguearse en su cuenta de Google y aceptar la pantalla de consentimiento configurada en los pasos previos.
 - Si el usuario acepta, Google lo redirigirá a mi aplicación en la ruta configurada en los pasos previos, añadiendole como parámetro un código de autorización (ej: `URI?code=AUTHORIZATION_CODE&...`)
 - Mi aplicación incluye el código de acceso en una solicitud interna a Google el cual responde con un token de aceso.
 - El token de acceso se usa para obtener los recursos especificados (en este caso los datos de la cuenta de Google del usuario)

**Comment by salva200** [comment]
De las librerías se destacan las clases:
- [vendor/google/apiclient/src/Client.php](https://googleapis.github.io/google-api-php-client/main/Google/Client.html) (Cliente de la API de Google)
- [vendor/google/apiclient-services/src/Oauth2.php](https://github.com/googleapis/google-api-php-client-services/blob/main/src/Oauth2.php) (Servicio OAuth)

Se implementan en la nueva carpeta `src/services/GoogleAuthController.php`.


**carpeta `services`**  
	 Funciones que representan reglas de negocio o lógica específica de la aplicación. Suelen interactuar con una dependencia externa (ej: API externa)

**carpeta `utils`**  
	Funciones de ayuda reutilizables y genéricas.

**Comment by salva200** [comment]
La sesión del usuario autenticado persiste temporalmente a través de la variable global `$_SESSION`.

Se guardan los usuarios autenticados en la tabla `user` para llevar un control de los mismos.
```mysql
CREATE TABLE user (
	id int PRIMARY KEY AUTO_INCREMENT,
	firstname varchar(255) NOT NULL,
	lastname varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	img_url varchar(255) NOT NULL,
	verified_email int NOT NULL,
	google_id varchar(255) NOT NULL,
	created_at datetime DEFAULT CURRENT_TIMESTAMP -- fecha-hora actual por defecto
);
```
